### PR TITLE
making game faster

### PR DESCRIPTION
**Pull request by tnayagarwal**

### CODE REVIEW

**Comment by tnayagarwal** [comment]
@PhoenixFlame101 hope its not too fast haha

**Comment by PhoenixFlame101** [comment]
Only change the paddle and ball speeds in the main variable, don't change the delta multiplier. Also make sure they are the same speed so the game is still possible at higher speeds

**Comment by tnayagarwal** [comment]
cool cool @PhoenixFlame101

**Comment by tnayagarwal** [comment]
fixed it bro 👍

**Comment by PhoenixFlame101** [comment]
You're still changing the delta multiplier, and the speeds aren't the same (235 and 255)

**Comment by tnayagarwal** [comment]
@PhoenixFlame101 so i get what u mean with the delta, ive just removed one whitespace im sure the code works without it. ive made the speeds same but i can send another pr for the delta to have the same syntax but i dont want to spam pr so its upto you ill do what u say

**Comment by tnayagarwal** [comment]
@PhoenixFlame101 speeds increased, both paddle and ball speed are same and ive changed the syntax for the delta so it shouldnt say the value was changed now

**Comment by PhoenixFlame101** [comment]
Cool, good job

**Comment by PhoenixFlame101** [comment]
!bounty 20

**Comment by tnayagarwal** [comment]
hey @PhoenixFlame101 didnt get my bounty could u check once

**Comment by PhoenixFlame101** [comment]
!bounty 20

**Pull request merged**
