### PR TITLE
Ball changes direction depending on loser

### LINKED ISSUE #9: The ball only moves to the left
Whenever the game restarts, the ball always goes to the left. I can make it alternate from left to right every alternate round to improve the experience.

### PR DESCRIPTION
**Pull request by mokshablr**
Fixes #9

### CODE REVIEW

**Comment by PhoenixFlame101** [comment]
Great effort! Here's some issues with your PR right now:

 - Ball continues in the direction it was travelling when the game ended; the ball should move only horizontally
 - The speed variable is unnecessarily changed; keep it the same as the original

**Comment by mokshablr** [comment]
I'll try work on the direction changing. As for the change in speed variable, I had done it earlier when there was an issue to make it faster.

Can I get a point just for the changing direction contribution? Just wanna be on the leaderboard. No worries if its not possible :)

**Comment by PhoenixFlame101** [comment]
Don't give up so quickly, you're really close to the solution. Try your best till the end of the event!

**Comment by PhoenixFlame101** [comment]
!bounty 10

**Pull request closed without merging**
